server:
  port: 7923

spring:
  security:
    user:
      name: "photowey"
      password: "photowey@github.com"

# ---------------------------------------------------------------------

logging:
  level:
    root: INFO
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %red([%X{traceId}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) %cyan(%msg%n) %ex{10}'